export const CREATE_COUPON_REQUEST = 'CREATE_COUPON_REQUEST'
export const CREATE_COUPON_SUCCESS = 'CREATE_COUPON_SUCCESS'
export const CREATE_COUPON_FAIL = 'CREATE_COUPON_FAIL'
export const CREATE_COUPON_RESET = 'CREATE_COUPON_RESET'


export const GET_ALL_COUPONS = 'GET_ALL_COUPONS'

export const DELETE_COUPON = 'DELETE_COUPON'
export const  DELETE_COUPON_RESET = ' DELETE_COUPON_RESET'