export const GET_ALL_SUBCATEGORIES_REQUEST = 'GET_ALL_SUBCATEGORIES_REQUEST'
export const GET_ALL_SUBCATEGORIES_SUCCESS = 'GET_ALL_SUBCATEGORIES_SUCCESS'
export const GET_ALL_SUBCATEGORIES_FAIL = 'GET_ALL_SUBCATEGORIES_FAIL'


export const GET_SINGLE_SUBCATEGORY_REQUEST = 'GET_SINGLE_SUBCATEGORY_REQUEST'
export const GET_SINGLE_SUBCATEGORY_SUCCESS = 'GET_SINGLE_SUBCATEGORY_SUCCESS'
export const GET_SINGLE_SUBCATEGORY_FAIL = 'GET_SINGLE_SUBCATEGORY_FAIL'


export const CREATE_SUBCATEGORY_REQUEST = 'CREATE_SUBCATEGORY_REQUEST'
export const CREATE_SUBCATEGORY_SUCCESS = 'CREATE_SUBCATEGORY_SUCCESS'
export const CREATE_SUBCATEGORY_FAIL = 'CREATE_SUBCATEGORY_FAIL'
export const CREATE_SUBCATEGORY_RESET = 'CREATE_SUBCATEGORY_RESET'

export const UPDATE_SUBCATEGORY_REQUEST = 'UPDATE_SUBCATEGORY_REQUEST'
export const UPDATE_SUBCATEGORY_SUCCESS = 'UPDATE_SUBCATEGORY_SUCCESS'
export const UPDATE_SUBCATEGORY_FAIL = 'UPDATE_SUBCATEGORY_FAIL'
export const UPDATE_SUBCATEGORY_RESET = 'UPDATE_SUBCATEGORY_RESET'

export const DELETE_SUBCATEGORY_REQUEST = 'DELETE_SUBCATEGORY_REQUEST'
export const DELETE_SUBCATEGORY_SUCCESS = 'DELETE_SUBCATEGORY_SUCCESS'
export const DELETE_SUBCATEGORY_FAIL = 'DELETE_SUBCATEGORY_FAIL'
export const DELETE_SUBCATEGORY_RESET = 'DELETE_SUBCATEGORY_RESET'