export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_ITEM_CART = 'REMOVE_FROM_CART'
export const SAVE_SHIPPING_INFO = 'SAVE_SHIPPING_INFO'
export const RESET_CART = 'RESET_CART'

export const GET_USER_CART_REQUEST = 'GET_USER_CART_REQUEST'
export const GET_USER_CART_SUCCESS = 'GET_USER_CART_SUCCESS'
export const GET_USER_CART_FAIL = 'GET_USER_CART_FAIL'

export const GET_USER_CART = 'GET_USER_CART'
export const EMPTY_CART = 'EMPTY_CART'


export const ADD_USER_CART_REQUEST = 'ADD_USER_CART_REQUEST'
export const ADD_USER_CART = 'ADD_USER_CART'

export const REMOVE_USER_CART = 'REMOVE_USER_CART'
