export const GET_ALL_CATEGORIES_REQUEST = 'GET_ALL_CATEGORIES_REQUEST'
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS'
export const GET_ALL_CATEGORIES_FAIL = 'GET_ALL_CATEGORIES_FAIL'


export const GET_SINGLE_CATEGORY_REQUEST = 'GET_SINGLE_CATEGORY_REQUEST'
export const GET_SINGLE_CATEGORY_SUCCESS = 'GET_SINGLE_CATEGORY_SUCCESS'
export const GET_SINGLE_CATEGORY_FAIL = 'GET_SINGLE_CATEGORY_FAIL'



export const GET_SUBS_BY_CATEGORY_REQUEST = 'GET_SUBS_BY_CATEGORY_REQUEST'
export const GET_SUBS_BY_CATEGORY_SUCCESS = 'GET_SUBS_BY_CATEGORY_SUCCESS'
export const GET_SUBS_BY_CATEGORY_FAIL = 'GET_SUBS_BY_CATEGORY_FAIL'
export const GET_SUBS_BY_CATEGORY_RESET = 'GET_SUBS_BY_CATEGORY_RESET'