export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST'
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS'
export const GET_ALL_PRODUCTS_FAIL = 'GET_ALL_PRODUCTS_FAIL'


export const GET_SINGLE_PRODUCT_REQUEST = 'GET_SINGLE_PRODUCT_REQUEST'
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS'
export const GET_SINGLE_PRODUCT_FAIL = 'GET_SINGLE_PRODUCT_FAIL'

export const GET_PRODUCTS_POST_REQUEST = 'GET_PRODUCTS_POST_REQUEST'
export const GET_PRODUCTS_POST_SUCCESS = 'GET_PRODUCTS_POST_SUCCESS'
export const GET_PRODUCTS_POST_FAIL = 'GET_PRODUCTS_POST_FAIL'
export const GET_PRODUCTS_BEST_POST_SUCCESS = 'GET_PRODUCTS_BEST_POST_SUCCESS' 


export const GET_TOTAL_PRODUCT_REQUEST = 'GET_TOTAL_PRODUCT_REQUEST'
export const GET_TOTAL_PRODUCT_SUCCESS = 'GET_TOTAL_PRODUCT_SUCCESS'
export const GET_TOTAL_PRODUCT_FAIL = 'GET_TOTAL_PRODUCT_FAIL'


export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS'
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'


export const GET_RELATED_PRODUCT_REQUEST = 'GET_RELATED_PRODUCT_REQUEST'
export const GET_RELATED_PRODUCT_SUCCESS = 'GET_RELATED_PRODUCT_SUCCESS'
export const GET_RELATED_PRODUCT_FAIL = 'GET_RELATED_PRODUCT_FAIL'
export const GET_RELATED_PRODUCT_RESET = 'GET_RELATED_PRODUCT_RESET'


export const PRODUCT_POST_FILTER_REQUEST = 'PRODUCT_POST_FILTER_REQUEST'
export const PRODUCT_POST_FILTER_SUCCESS = 'PRODUCT_POST_FILTER_SUCCESS'
export const PRODUCT_POST_FILTER_FAIL = 'PRODUCT_POST_FILTER_FAIL'
export const PRODUCT_POST_FILTER_RESET = 'PRODUCT_POST_FILTER_RESET'