export const STRIPE_APPLY_REQUEST = 'STRIPE_APPLY_REQUEST'
export const STRIPE_APPLY_SUCCESS = 'STRIPE_APPLY_SUCCESS'
export const STRIPE_APPLY_FAIL= 'STRIPE_APPLY_FAIL'
export const STRIPE_APPLY_RESET= 'STRIPE_APPLY_RESET'