export const GET_ALL_SUBCATEGORIES_REQUEST = 'GET_ALL_SUBCATEGORIES_REQUEST'
export const GET_ALL_SUBCATEGORIES_SUCCESS = 'GET_ALL_SUBCATEGORIES_SUCCESS'
export const GET_ALL_SUBCATEGORIES_FAIL = 'GET_ALL_SUBCATEGORIES_FAIL'


export const GET_SINGLE_SUBCATEGORY_REQUEST = 'GET_SINGLE_SUBCATEGORY_REQUEST'
export const GET_SINGLE_SUBCATEGORY_SUCCESS = 'GET_SINGLE_SUBCATEGORY_SUCCESS'
export const GET_SINGLE_SUBCATEGORY_FAIL = 'GET_SINGLE_SUBCATEGORY_FAIL'
